os: linux
dist: focal
language: generic
services:
  - docker

jobs:
  include:
    - stage: ChemistryValley build
      script:
      - |
        cd Demos/ValleeChimie
        docker build -t vallee-chimie ud-viz-context 
