os: linux
dist: focal
language: generic
services:
  - docker

jobs:
  include:
    - stage: ChemistryValley build
      script:
      - |
        cd Demos/ValleeChimie
        docker build -t vallee-chimie ud-viz-context 
    - stage: DatAgora_PartDieu build
      script:
      - |
        cd Demos/DatAgora_PartDieu
        docker-compose --version
        docker-compose build
