apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: parameters-
spec:
  entrypoint: main
  volumes:
  - name: workdir
    hostPath:
      path: /data/host
  arguments:
    parameters:
    # Numerical experiment related
    - name: boroughs
    - name: pattern
    - name: vintage
    - name: experiment_output_dir
    # Local (to this workflow definition) parameters   
    - name: persistedVolume   
      value: /within-container-mount-point/

  templates:
  - name: main
    steps:
    
    # Warning: this assumes that just-split (stage 2) was ran before
    - - name: strip-gml-loop
        templateRef:
          name: workflow-template-atomic-steps-templaterefs
          template: strip-gml-template
        arguments:
          parameters:
          - name: input_filename
            value: "{{workflow.parameters.experiment_output_dir}}/stage_2/{{workflow.parameters.vintage}}/{{item}}_{{workflow.parameters.vintage}}/{{item}}_{{workflow.parameters.pattern}}_{{workflow.parameters.vintage}}_split.gml"
          - name: output_dir
            value: "{{workflow.parameters.experiment_output_dir}}/stage_3/{{workflow.parameters.vintage}}/{{item}}_{{workflow.parameters.vintage}}"
          - name: output_filename
            value: "{{item}}_{{workflow.parameters.pattern}}_{{workflow.parameters.vintage}}_stripped.gml"
          - name: persistedVolume
            value: "{{workflow.parameters.persistedVolume}}"
        withParam: "{{workflow.parameters.boroughs}}"

    - - name: print-file-names
        templateRef:
          name: workflow-template-utils-whalesay-template
          template: whalesay-template
        arguments:
          parameters:
          - name: message
            value: "{{steps.strip-gml-loop.outputs.parameters.resulting-filenames}}"
            