apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: parameters-
spec:
  entrypoint: main
  volumes:
  - name: workdir
    hostPath:
      path: /data/host
  arguments:
    parameters:
    - name: persistedVolume   
      value: /within-container-mount-point/

  templates:
  - name: main
    steps:
    - - name: collect-boroughs
        templateRef:
          name: workflow-template-atomic-steps-template
          template: collect-lyon-data-template
        arguments:
          parameters:
          - name: borough
            value: "{{item}}"
          - name: pattern
            value: "{{workflow.parameters.pattern}}"
          - name: results_dir
            value: "{{workflow.parameters.experiment_output_dir}}/stage_1/{{item}}_{{workflow.parameters.vintage}}"
          - name: vintage
            value: "{{workflow.parameters.vintage}}"
          - name: persistedVolume
            value: "{{workflow.parameters.persistedVolume}}"
        withParam: "{{workflow.parameters.boroughs}}"
            
    - - name: print-file-names
        templateRef:
          name: workflow-template-utils-whalesay-template
          template: whalesay-template
        arguments:
          parameters:
          - name: message
            value: "{{steps.collect-boroughs.outputs.parameters.resulting-filenames}}"
