apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: parameters-
spec:
  entrypoint: main
  volumes:
  - name: workdir
    persistentVolumeClaim:
      claimName: vcity-pvc
      readOnly: false
  arguments:
    parameters:
    # Numerical experiment related
    - name: boroughs
    - name: pattern
    - name: vintage
    - name: experiment_output_dir
    # Depending on your execution context
    - name: dockerRegistryHost
      value: ""
    # Local (to this workflow definition) parameters   
    - name: persistedVolume   
      value: /within-container-mount-point/

  templates:
  - name: main
    steps:
    
    # Warning: this assumes that just-collect was ran before
    - - name: split-buildings-loop
        templateRef:
          name: workflow-template-atomic-steps-templaterefs
          template: split-buildings-template
        arguments:
          parameters:
          - name: input_filename
            value: "{{workflow.parameters.experiment_output_dir}}/stage_1/{{workflow.parameters.vintage}}/{{item}}_{{workflow.parameters.vintage}}/{{item}}_{{workflow.parameters.pattern}}_{{workflow.parameters.vintage}}.gml"
          - name: output_dir
            value: "{{workflow.parameters.experiment_output_dir}}/stage_2/{{workflow.parameters.vintage}}/{{item}}_{{workflow.parameters.vintage}}"
          - name: output_filename
            value: "{{item}}_{{workflow.parameters.pattern}}_{{workflow.parameters.vintage}}_split.gml"
          - name: dockerRegistryHost
            value: "{{workflow.parameters.dockerRegistryHost}}"
          - name: persistedVolume
            value: "{{workflow.parameters.persistedVolume}}"
        withParam: "{{workflow.parameters.boroughs}}"

    - - name: print-file-names
        templateRef:
          name: workflow-template-utils-whalesay-template
          template: whalesay-template
        arguments:
          parameters:
          - name: message
            value: "{{steps.split-buildings-loop.outputs.parameters.resulting-filenames}}"
