apiVersion: batch/v1
kind: Job
metadata:
  name: pi
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: pi
          image: perl
          command: ["perl", "-Mbignum=bpi", "-wle", "print bpi(2000)"]
          volumeMounts:
            - mountPath: /data/host
              name: minikube-vol
      volumes:
        - name: minikube-vol
          persistentVolumeClaim:
            claimName: minikube-pvc
      restartPolicy: Never
  backoffLimit: 4
