---
## Zombie pod that has no other purpose than allowing to navigate with a shell,
# executed in the pod, the directory-tree/files resulting from the execution
# of some argo workflow (using that PVC) execution.
# Because this definition uses replicas the name of the pod get postfixed with
# various numbers (e.g. vcity-handler-8b78b6875-v6p8k).
# In order to exec a shell in the pod, first retrieve its name with e.g.
#      k -n argo get pod | grep vcity-handler
# that will return e.g. vcity-handler-8b78b6875-v6p8k that can be used with
# k -n argo exec -it vcity-handler-8b78b6875-v6p8k -- bash
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: vcity-handler
  name: vcity-handler
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vcity-handler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vcity-handler
    spec:
      containers:
      - image: ubuntu:22.04
        imagePullPolicy: IfNotPresent
        name:  data-container
        command: ['/bin/sh', '-c']
        args:
          - "tail -f /var/log/lastlog"
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: vcity-pvc
            readOnly: false
      restartPolicy: Always
