---
## Zombie pod that has no other purpose than allowing to navigate
# within the directory-tree/files that this volume gathered after
# being used by some argo workflow (using that PVC) execution.
# FIXME: do
apiVersion: v1
kind: Pod
metadata:
  name: vcity-pvc-nginx-pod
  namespace: argo
spec:
  containers:
    - name: web-server
      image: docker.io/library/nginx:latest
      volumeMounts:
        - name: mypvc
          mountPath: /var/lib/www/html
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: vcity-pvc
        readOnly: false

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: vcity-handler
  name: vcity-handler
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vcity-handler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vcity-handler
    spec:
      containers:
      - image: ubuntu:22.04
        imagePullPolicy: IfNotPresent
        name:  data-container
        command: ['/bin/sh', '-c']
        args:
          - "tail -f /var/log/lastlog"
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: vcity-pvc
            readOnly: false
      restartPolicy: Always
