version: "3.8"
# Notes concerning the exposed ports:
# * the JS frontend will need to directly (that is from the client running
#   in the web browser) access to the two services the demo requires that
#   are the bim server and the 3dTiles server.
#   This implies that the two services will be referred (from the client's
#   JS code) to with an address of the form `http://localhost:<port>/` (as
#   opposed to `http://bim-server:<port>/` (where bim-server is the 
#   docker-compose service name defined below in this file)
# * This docker-compose chooses to expose three consecutive ports (8090,
#   8091 and 8092) in order to facilitate the site fire-wall port opening.
#   Indeed it's easier to require/configure 8090-8092 to be opened instead
#   of opening each native service choices that would go (for this present
#   example) 80 (ud-viz), 8003 (3dtiles-samples) and 8080 (bim-server).
#   
services:

  3d-tiles-samples-server:
    build: ./3d-tiles-samples-context
    ports:
      - "8091:8003"

  udviz:
    build: ./ud-viz-context
    ports:
      - "8090:80"
