---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vcity-data
  namespace: argo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: ceph-filesystem
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: download-scripts
  labels:
    app.kubernetes.io/name: data-handler
data:
  download_data.sh: |
    #!/usr/bin/env bash
  
    tail -f /var/log/lastlog 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: data-handler
  name: data-handler
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: data-handler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: data-handler
    spec:
      containers:
      - image: ubuntu:22.04
        imagePullPolicy: IfNotPresent
        name:  data-container
        command: ['/bin/sh', '-c']
        args:
          - /download-scripts/download_data.sh
        volumeMounts:
        - mountPath: /data
          name: data
        - name: download-scripts
          mountPath: /download-scripts
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: vcity-data
            readOnly: false
        - name: download-scripts
          configMap:
            name: download-scripts
            defaultMode: 0744
      restartPolicy: Always
      