apiVersion: v1
kind: Secret
metadata:
  name: argo-user.service-account-token
  namespace: argo
  annotations:
    kubernetes.io/service-account.name: argo-user
type: kubernetes.io/service-account-token
