version: "3.8"

services:
  geoserver:
    image : kartoza/geoserver:2.18.0
    environment :
      - SAMPLE_DATA=true
    ports: 
      - "8080:8080"


  geoserver-setup:
    build : ./server-setup-context
    environment :
      - DATA_IMPORT_DIR=${GEOSERVER_DATA_IMPORT_DIR}
      - WORKSPACE=${GEOSERVER_WORKSPACE}
      - MAX_CONNECTION_ATTEMPTS=${GEOSERVER_MAX_CONNECTION_ATTEMPTS}
      - TIME_CONNECTION_ATTEMPTS=${GEOSERVER_TIME_CONNECTION_ATTEMPTS}


  udviz:
    build : ./ud-viz-context
    ports:
      - "8999:8999"
